puyo:
	gcc -c puyo01.c
	gcc -c kbhit.c
	gcc -g -wall puyo01.o kbhit.o -o puyo01 -lncurses

play:
	gcc -c puyo01.c
	gcc -c kbhit.c
	gcc -g -wall puyo01.o kbhit.o -o puyo01 -lncurses
	./puyo01

clean:
	rm kbhit.o
	rm test.o
	rm puyo01

